### ISSUE TITLE
token有效期好像是两周

### ISSUE THREAD

**Issue by 3405745457** [syrinka/dxx#1]

**Comment by syrinka** [comment]
如果是希望 token 能自动刷新的话……很遗憾我没什么思路，微信不信任系统证书，我抓不到和微信后端交互的包

若是你有什么方法的话请告知我

**Comment by 3405745457** [comment]
> 如果是希望 token 能自动刷新的话……很遗憾我没什么思路，微信不信任系统证书，我抓不到它和大学习后端交互的包
> 
> 若是你有什么方法的话请告知我

我手机抓了看了一下，好像没办法自动获取新的token，获取token需要有一个code我不了解是怎么来的
[token.zip](https://github.com/syrinka/sichuan-qndxx/files/9706058/token.zip)

**Comment by syrinka** [comment]
> > 如果是希望 token 能自动刷新的话……很遗憾我没什么思路，微信不信任系统证书，我抓不到它和大学习后端交互的包
> > 若是你有什么方法的话请告知我
> 
> 我手机抓了看了一下，好像没办法自动获取新的token，获取token需要有一个code我不了解是怎么来的 [token.zip](https://github.com/syrinka/sichuan-qndxx/files/9706058/token.zip)

微信小程序用的似乎是魔改的 OAuth2 认证，这个 code 是其中的一步，是向微信后端请求获得的

基本上抓不到发向微信后端的包就无法获得 code，想自动刷新 token 就更不可能了
